### ISSUE TITLE
Trackpad not working

### ISSUE THREAD

**Issue by avelarfe** [hansyao/Hackintosh_Monterey_M4800#1]
Hello, i have the same spec that you have (except for de wifi that is an intel one) and my trackpad is not working.

what is your bios configuration?

i have the latest bios installed.

**Comment by avelarfe** [comment]
Also: I’ll try again later the win+alt solution.

**Comment by hansyao** [comment]
For Intel WIFI adapter, you may remove below 4 kexts from my EFI package and instead of appropriate [Intel driver](https://openintelwireless.github.io/). In the meanwhile, you can remove [line 1379-1408](../blob/master/SSDT-Dell-M4800.dsl#L1379-L1408)  in dsl file [SSDT-Dell-M4800.dsl](../blob/master/SSDT-Dell-M4800.dsl), and then recompile to replace [SSDT-Dell-M4800.aml](../blob/master/EFI/OC/ACPI/SSDT-Dell-M4800.aml).
```s
AirportBrcmFixup.kext
BlueToolFixup.kext
BrcmFirmwareData.kext
BrcmPatchRAM3.kext
```
For other kexts, you could use my kexts in EFI package but please **DO NOT** upgrade to officials because some of my kexts have some modifications to adapt ACPI structure.

**Comment by avelarfe** [comment]
I’ll try the intel one, but how do i recompile? Is there any guide?

**Comment by hansyao** [comment]
probably also works if not recompile aml. anyway you can try it.

**Comment by avelarfe** [comment]
Din't had to recompile (even tho I don't know how), both wifi and bluetooth are working with the intel kexts. Also, the trackpad only works when holding win+alt until boot :/

**Comment by hansyao** [comment]
> the trackpad only works when holding win+alt until boot

Ok. It seems the problem solved. It’s the known bug `the trackpad works when holding win+alt until boot` that you don’t need to attempt to solve it now.

**Comment by hansyao** [comment]
this issue was fixed. no need hold <kbd>win</kbd>+<kbd>alt</kbd> any longer.
